### ISSUE TITLE
ip route get

### ISSUE THREAD

**Issue by ItsFunny** [yl2chen/cidranger#11]
could i get gateway over this by a specific host

**Comment by yl2chen** [comment]
This what you looking for? https://github.com/yl2chen/cidranger/blob/master/cidranger.go#L74

```golang
// ContainingNetworks returns the list of RangerEntry(s) the given ip is
// contained in in ascending prefix order.
func (p *prefixTrie) ContainingNetworks(ip net.IP) ([]RangerEntry, error)
```

**Comment by ItsFunny** [comment]
**Thx**,I forget to close the issue ,i have already fixed the pro
