### ISSUE TITLE
memory leak - removes do not get garbage collected

### ISSUE THREAD

**Issue by danmia** [yl2chen/cidranger#15]
I'm noticing a behavior where deleted entries seem to not get reaped by garbage collection(runnable example below).  For example if I add 1,000,000 entries and then Remove() them all and force a garbage collection, the ranger hangs onto the majority of the memory.  If runs to 5 or so, you will see that it just grows and grows.  Is this known?  I took a look at the code but it's a bit hard for me to follow (as is most code I didn't write ;)

### Usage
```./cidrtest -ips 1000000 -runs 5```

### Sample Output
```
STARTING RUN 0
Starting Inserts
1000000 Inserts Complete
Observe Memory START Alloc = 615 MiB	TotalAlloc = 1828 MiB	Sys = 823 MiB	NumGC = 23
Starting Removes
ENDING RUN 0
Observe Memory END Alloc = 546 MiB	TotalAlloc = 2688 MiB	Sys = 3624 MiB	NumGC = 26
...
STARTING RUN 4
Starting Inserts
1000000 Inserts Complete
Observe Memory START Alloc = 1164 MiB	TotalAlloc = 11699 MiB	Sys = 4585 MiB	NumGC = 39
Starting Removes
ENDING RUN 4
Observe Memory END Alloc = 898 MiB	TotalAlloc = 12350 MiB	Sys = 4654 MiB	NumGC = 40
```

### Code
```go
package main

import (
	"encoding/binary"
	"flag"
	"fmt"
	"math/rand"
	"net"
	"runtime"
	"time"

	"github.com/yl2chen/cidranger"
)

func main() {

	ips := flag.Int("ips", 1000, "Number of IPs.  Default 1000")
	runs := flag.Int("runs", 1000, "Number of runs.  Default 2")
	flag.Parse()

	mask := net.CIDRMask(32, 32)
	trie := cidranger.NewPCTrieRanger()

	// Main loop
	for i := 0; i < *runs; i++ {
		fmt.Printf("STARTING RUN %d\n", i)
		fmt.Printf("Starting Inserts\n")
		for n := 0; n < *ips; n++ {
			trie.Insert(cidranger.NewBasicRangerEntry(net.IPNet{
				IP:   GenIPV4(),
				Mask: mask,
			}))
		}

		fmt.Printf("%d Inserts Complete\n", *ips)
		time.Sleep(5 * time.Second)
		fmt.Printf("Observe Memory START ")
		PrintMemUsage()
		fmt.Printf("Starting Removes\n")
		_, all, _ := net.ParseCIDR("0.0.0.0/0")
		ll, _ := trie.CoveredNetworks(*all)
		for i := 0; i < len(ll); i++ {
			trie.Remove(ll[i].Network())
		}
		ll = nil
		fmt.Printf("ENDING RUN %d\n", i)
		fmt.Printf("Observe Memory END ")
		runtime.GC()
		PrintMemUsage()
		time.Sleep(5 * time.Second)
	}
}

// GenIPV4 generates an IPV4 address
func GenIPV4() net.IP {
	rand.Seed(time.Now().UnixNano())
	var min, max int
	min = 1
	max = 4294967295
	nn := rand.Intn(max-min) + min
	ip := make(net.IP, 4)
	binary.BigEndian.PutUint32(ip, uint32(nn))
	return ip
}

// PrintMemUsage dumps memory stats for the process
func PrintMemUsage() {
	var m runtime.MemStats
	runtime.ReadMemStats(&m)
	fmt.Printf("Alloc = %v MiB", bToMb(m.Alloc))
	fmt.Printf("\tTotalAlloc = %v MiB", bToMb(m.TotalAlloc))
	fmt.Printf("\tSys = %v MiB", bToMb(m.Sys))
	fmt.Printf("\tNumGC = %v\n", m.NumGC)
}

func bToMb(b uint64) uint64 {
	return b / 1024 / 1024
}
```

**Comment by mudream4869** [comment]
The code actually does not remove **ALL** networks. 
```
_, all, _ := net.ParseCIDR("0.0.0.0/0")
ll, _ := trie.CoveredNetworks(*all)
for i := 0; i < len(ll); i++ {
	trie.Remove(ll[i].Network())
}
```
For example, if we first insert "192.168.1.0/24" and "192.168.1.1/32", then try to remove "all networks" by code snippet above, the trie will still leave "192.168.1.1/32".
The reason is that the **CoveredNetworks** function will only return one network **192.168.1.0/24** in the above case. The **Remove operation** is implemented as just remove the node but if any child exist then the child will leave.
https://play.golang.org/p/7NRBI_zBYb5

**Comment by yl2chen** [comment]
@danmia Thanks for posting the tests to show the memory leak, and sorry I only got to investigating now, I have provided the fix and incorporated your test in the unit test suite.

**Comment by yl2chen** [comment]
I will leave the PR unmerged for some time, to give you a chance to independently verify that the memory leak upon removal is addressed, thanks!

**Comment by danmia** [comment]
Thanks for looking into it!  It looks good in my local tests.  This is super useful.  Thanks again!
