### ISSUE TITLE
Iterating over the cidrs

### ISSUE THREAD

**Issue by TomOnTime** [yl2chen/cidranger#5]
Hi!

Two questions:

I created a ranger and inserted a few entries.  Is there a way to iterate over the list of CIDR blocks?

Also, is there something like ranger.Contains() that returns the data instead of a bool?   I'm using something that implements the RangerEntry interface and I'd like to get back the entire thing.

Thanks!

**Comment by yl2chen** [comment]
Hi Tom,

If you look at https://github.com/yl2chen/cidranger/blob/master/trie.go#L290 , it does have capability to iterate over the inserted blocks, but I have not exposed it as a public interface.  I will work on making that public this weekend.

```ContainingNetworks``` will return all RangerEntry items given ip is a part of.

Yulin

**Comment by jhg03a** [comment]
Any update on this?  I'd like to see if I can use it to get a list of CIDRs having been reduced for overlapping/adjacency.

**Comment by yl2chen** [comment]
Sorry didn't have time to work on this, but you are welcome to create a PR! thanks!
